accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home'),

    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [
    url(r'^index/$', post_index, name='index'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home_view(request):
    if request.user.is_authenticated:

        context = {
            'ad': "Mahir"

        }
    else:
        context = {
            'ad': 'Qonaq'
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %} Django sayti {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
{% include 'header.html' %}
{% include 'messages.html' %}


{% block body %}

{% endblock %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'home' %}">Dangtor</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

        <a class="nav-link" href="{% url 'home' %}">Ana Səhifə <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'post:index' %}">Blog</a>
      </li>
         <li class="nav-item">
              {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'post:create' %}">Bloga elave et</a>
             {% endif %}
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Haqqimda</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Əlaqə</a>
        </li>
        {% if not request.user.is_authenticated %}
            <li>
                <a class="nav-link" href="{% url 'accounts:register' %}">Qeydiyyat</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'accounts:login' %}">Giriş</a>
            </li>
        {% else %}
            <li>
                <a class="nav-link" href="{% url 'accounts:logout' %}">Çıxış</a>
            </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}" type="search" placeholder="Saytda axtar" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Saytda axtar</button>
    </form>
  </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %} Ana sehife - {{block.super}} {% endblock %}

{% block body %}

{#    <div class="container-fluid">#}
{#        <div class="row" style="margin-bottom: 30px">#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: red; height:100px">1. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #0099ff; height:100px">2. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #00ef16; height:100px">3. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ffdc03; height:100px">4. sutun</div>#}
{#        </div>#}
{#    </div>#}
{##}
{##}
{#    <div class="container-fluid">#}
{#        <div class="row" style="margin-bottom: 30px">#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: red; height:100px">1. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #0099ff; height:100px">2. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #00ef16; height:100px">3. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ffdc03; height:100px">4. sutun</div>#}
{#        </div>#}
{#    </div>#}
{#    <div class="container-fluid">#}
{#        <div class="row" style="margin-bottom: 30px">#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: red; height:100px">1. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #0099ff; height:100px">2. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #00ef16; height:100px">3. sutun</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ffdc03; height:100px">4. sutun</div>#}
{#        </div>#}
{#    </div>#}
    <div class="row">
    <div class="col-md-10" style="background-color: red; height: 100px;"></div>
    <div class="col-md-4" style="background-color: #16c419; height: 100px;"></div>

    Xosgeldin, {{ request.user.get_full_name }}

    </div>


{% endblock %}

templates/messages.html
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
{#    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}></li>#}
    {% endfor %}

{% endif %}